#include "common.h"

int GEngine::WINDOW_CONFIG::WINDOW_WIDTH = 800;
int GEngine::WINDOW_CONFIG::WINDOW_HEIGHT = 600;
int GEngine::WINDOW_CONFIG::VIEWPORT_LOWERLEFT_X = 0;
int GEngine::WINDOW_CONFIG::VIEWPORT_LOWERLEFT_Y = 0;
int GEngine::WINDOW_CONFIG::VIEWPORT_WIDTH = GEngine::WINDOW_CONFIG::WINDOW_WIDTH;
int GEngine::WINDOW_CONFIG::VIEWPORT_HEIGHT = GEngine::WINDOW_CONFIG::WINDOW_HEIGHT;
std::string GEngine::WINDOW_CONFIG::WINDOW_TITLE = "GEngine";
bool GEngine::WINDOW_CONFIG::IS_CURSOR_DISABLED = false;